#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 11
#define STATE_COUNT 88
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 61
#define ALIAS_COUNT 0
#define TOKEN_COUNT 31
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 7

enum {
  sym_identifier = 1,
  anon_sym_LBRACK = 2,
  anon_sym_RBRACK = 3,
  anon_sym_SEMI = 4,
  anon_sym_int = 5,
  anon_sym_void = 6,
  anon_sym_bool = 7,
  anon_sym_LPAREN = 8,
  anon_sym_COMMA = 9,
  anon_sym_RPAREN = 10,
  anon_sym_LBRACE = 11,
  anon_sym_RBRACE = 12,
  anon_sym_if = 13,
  anon_sym_else = 14,
  anon_sym_while = 15,
  anon_sym_return = 16,
  anon_sym_GT = 17,
  anon_sym_GT_EQ = 18,
  anon_sym_LT = 19,
  anon_sym_LT_EQ = 20,
  anon_sym_EQ_EQ = 21,
  anon_sym_BANG_EQ = 22,
  anon_sym_PLUS = 23,
  anon_sym_DASH = 24,
  anon_sym_STAR = 25,
  anon_sym_SLASH = 26,
  anon_sym_EQ = 27,
  sym_num_literal = 28,
  anon_sym_true = 29,
  anon_sym_false = 30,
  sym_program = 31,
  sym__declaration = 32,
  sym_var_declaration = 33,
  sym_type_specifier = 34,
  sym_function_declaration = 35,
  sym_param_list = 36,
  sym_param = 37,
  sym_compound_statement = 38,
  sym__statement = 39,
  sym_selection_statement = 40,
  sym_iteration_statement = 41,
  sym_return_statement = 42,
  sym_expression_statement = 43,
  sym__expression = 44,
  sym__simple_expression = 45,
  sym_binary_expression = 46,
  sym_rel_op = 47,
  sym_add_op = 48,
  sym_mul_op = 49,
  sym__factor = 50,
  sym_call_expression = 51,
  sym_arg_list = 52,
  sym_assignment = 53,
  sym_variable = 54,
  sym_boolean_literal = 55,
  aux_sym_program_repeat1 = 56,
  aux_sym_param_list_repeat1 = 57,
  aux_sym_compound_statement_repeat1 = 58,
  aux_sym_compound_statement_repeat2 = 59,
  aux_sym_arg_list_repeat1 = 60,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_SEMI] = ";",
  [anon_sym_int] = "int",
  [anon_sym_void] = "void",
  [anon_sym_bool] = "bool",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_while] = "while",
  [anon_sym_return] = "return",
  [anon_sym_GT] = ">",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT] = "<",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_EQ] = "=",
  [sym_num_literal] = "num_literal",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_program] = "program",
  [sym__declaration] = "_declaration",
  [sym_var_declaration] = "var_declaration",
  [sym_type_specifier] = "type_specifier",
  [sym_function_declaration] = "function_declaration",
  [sym_param_list] = "param_list",
  [sym_param] = "param",
  [sym_compound_statement] = "compound_statement",
  [sym__statement] = "_statement",
  [sym_selection_statement] = "selection_statement",
  [sym_iteration_statement] = "iteration_statement",
  [sym_return_statement] = "return_statement",
  [sym_expression_statement] = "expression_statement",
  [sym__expression] = "_expression",
  [sym__simple_expression] = "_simple_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_rel_op] = "rel_op",
  [sym_add_op] = "add_op",
  [sym_mul_op] = "mul_op",
  [sym__factor] = "_factor",
  [sym_call_expression] = "call_expression",
  [sym_arg_list] = "arg_list",
  [sym_assignment] = "assignment",
  [sym_variable] = "variable",
  [sym_boolean_literal] = "boolean_literal",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_param_list_repeat1] = "param_list_repeat1",
  [aux_sym_compound_statement_repeat1] = "compound_statement_repeat1",
  [aux_sym_compound_statement_repeat2] = "compound_statement_repeat2",
  [aux_sym_arg_list_repeat1] = "arg_list_repeat1",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_int] = anon_sym_int,
  [anon_sym_void] = anon_sym_void,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_num_literal] = sym_num_literal,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_program] = sym_program,
  [sym__declaration] = sym__declaration,
  [sym_var_declaration] = sym_var_declaration,
  [sym_type_specifier] = sym_type_specifier,
  [sym_function_declaration] = sym_function_declaration,
  [sym_param_list] = sym_param_list,
  [sym_param] = sym_param,
  [sym_compound_statement] = sym_compound_statement,
  [sym__statement] = sym__statement,
  [sym_selection_statement] = sym_selection_statement,
  [sym_iteration_statement] = sym_iteration_statement,
  [sym_return_statement] = sym_return_statement,
  [sym_expression_statement] = sym_expression_statement,
  [sym__expression] = sym__expression,
  [sym__simple_expression] = sym__simple_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_rel_op] = sym_rel_op,
  [sym_add_op] = sym_add_op,
  [sym_mul_op] = sym_mul_op,
  [sym__factor] = sym__factor,
  [sym_call_expression] = sym_call_expression,
  [sym_arg_list] = sym_arg_list,
  [sym_assignment] = sym_assignment,
  [sym_variable] = sym_variable,
  [sym_boolean_literal] = sym_boolean_literal,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_param_list_repeat1] = aux_sym_param_list_repeat1,
  [aux_sym_compound_statement_repeat1] = aux_sym_compound_statement_repeat1,
  [aux_sym_compound_statement_repeat2] = aux_sym_compound_statement_repeat2,
  [aux_sym_arg_list_repeat1] = aux_sym_arg_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_void] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_num_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym__declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_var_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_type_specifier] = {
    .visible = true,
    .named = true,
  },
  [sym_function_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_param_list] = {
    .visible = true,
    .named = true,
  },
  [sym_param] = {
    .visible = true,
    .named = true,
  },
  [sym_compound_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_selection_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_iteration_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__simple_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_rel_op] = {
    .visible = true,
    .named = true,
  },
  [sym_add_op] = {
    .visible = true,
    .named = true,
  },
  [sym_mul_op] = {
    .visible = true,
    .named = true,
  },
  [sym__factor] = {
    .visible = false,
    .named = true,
  },
  [sym_call_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_arg_list] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_param_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_compound_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_compound_statement_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arg_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_id = 1,
  field_left = 2,
  field_op = 3,
  field_right = 4,
  field_type = 5,
};

static const char *ts_field_names[] = {
  [0] = NULL,
  [field_id] = "id",
  [field_left] = "left",
  [field_op] = "op",
  [field_right] = "right",
  [field_type] = "type",
};

static const TSFieldMapSlice ts_field_map_slices[4] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 3},
  [3] = {.index = 5, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_id, 1},
    {field_type, 0},
  [2] =
    {field_left, 0},
    {field_op, 1},
    {field_right, 2},
  [5] =
    {field_left, 0},
    {field_right, 2},
};

static TSSymbol ts_alias_sequences[4][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(2);
      if (lookahead == '!') ADVANCE(1);
      if (lookahead == '(') ADVANCE(6);
      if (lookahead == ')') ADVANCE(8);
      if (lookahead == '*') ADVANCE(19);
      if (lookahead == '+') ADVANCE(17);
      if (lookahead == ',') ADVANCE(7);
      if (lookahead == '-') ADVANCE(18);
      if (lookahead == '/') ADVANCE(20);
      if (lookahead == ';') ADVANCE(5);
      if (lookahead == '<') ADVANCE(13);
      if (lookahead == '=') ADVANCE(21);
      if (lookahead == '>') ADVANCE(11);
      if (lookahead == '[') ADVANCE(3);
      if (lookahead == ']') ADVANCE(4);
      if (lookahead == '{') ADVANCE(9);
      if (lookahead == '}') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 1:
      if (lookahead == '=') ADVANCE(16);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(12);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(14);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(15);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_num_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'b') ADVANCE(1);
      if (lookahead == 'e') ADVANCE(2);
      if (lookahead == 'f') ADVANCE(3);
      if (lookahead == 'i') ADVANCE(4);
      if (lookahead == 'r') ADVANCE(5);
      if (lookahead == 't') ADVANCE(6);
      if (lookahead == 'v') ADVANCE(7);
      if (lookahead == 'w') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'o') ADVANCE(9);
      END_STATE();
    case 2:
      if (lookahead == 'l') ADVANCE(10);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(11);
      END_STATE();
    case 4:
      if (lookahead == 'f') ADVANCE(12);
      if (lookahead == 'n') ADVANCE(13);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(14);
      END_STATE();
    case 6:
      if (lookahead == 'r') ADVANCE(15);
      END_STATE();
    case 7:
      if (lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 8:
      if (lookahead == 'h') ADVANCE(17);
      END_STATE();
    case 9:
      if (lookahead == 'o') ADVANCE(18);
      END_STATE();
    case 10:
      if (lookahead == 's') ADVANCE(19);
      END_STATE();
    case 11:
      if (lookahead == 'l') ADVANCE(20);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 13:
      if (lookahead == 't') ADVANCE(21);
      END_STATE();
    case 14:
      if (lookahead == 't') ADVANCE(22);
      END_STATE();
    case 15:
      if (lookahead == 'u') ADVANCE(23);
      END_STATE();
    case 16:
      if (lookahead == 'i') ADVANCE(24);
      END_STATE();
    case 17:
      if (lookahead == 'i') ADVANCE(25);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(26);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(27);
      END_STATE();
    case 20:
      if (lookahead == 's') ADVANCE(28);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_int);
      END_STATE();
    case 22:
      if (lookahead == 'u') ADVANCE(29);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(30);
      END_STATE();
    case 24:
      if (lookahead == 'd') ADVANCE(31);
      END_STATE();
    case 25:
      if (lookahead == 'l') ADVANCE(32);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_bool);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 29:
      if (lookahead == 'r') ADVANCE(34);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_void);
      END_STATE();
    case 32:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 34:
      if (lookahead == 'n') ADVANCE(36);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_while);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_int] = ACTIONS(1),
    [anon_sym_void] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_num_literal] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
  },
  [1] = {
    [sym_program] = STATE(86),
    [sym__declaration] = STATE(55),
    [sym_var_declaration] = STATE(55),
    [sym_type_specifier] = STATE(84),
    [sym_function_declaration] = STATE(55),
    [aux_sym_program_repeat1] = STATE(55),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_int] = ACTIONS(5),
    [anon_sym_void] = ACTIONS(5),
    [anon_sym_bool] = ACTIONS(5),
  },
  [2] = {
    [sym_var_declaration] = STATE(3),
    [sym_type_specifier] = STATE(83),
    [sym_compound_statement] = STATE(6),
    [sym__statement] = STATE(6),
    [sym_selection_statement] = STATE(6),
    [sym_iteration_statement] = STATE(6),
    [sym_return_statement] = STATE(6),
    [sym_expression_statement] = STATE(6),
    [sym__expression] = STATE(32),
    [sym__simple_expression] = STATE(32),
    [sym_binary_expression] = STATE(32),
    [sym__factor] = STATE(32),
    [sym_call_expression] = STATE(32),
    [sym_assignment] = STATE(32),
    [sym_variable] = STATE(21),
    [sym_boolean_literal] = STATE(32),
    [aux_sym_compound_statement_repeat1] = STATE(3),
    [aux_sym_compound_statement_repeat2] = STATE(6),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_SEMI] = ACTIONS(9),
    [anon_sym_int] = ACTIONS(11),
    [anon_sym_void] = ACTIONS(11),
    [anon_sym_bool] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(17),
    [anon_sym_if] = ACTIONS(19),
    [anon_sym_while] = ACTIONS(21),
    [anon_sym_return] = ACTIONS(23),
    [sym_num_literal] = ACTIONS(25),
    [anon_sym_true] = ACTIONS(27),
    [anon_sym_false] = ACTIONS(27),
  },
  [3] = {
    [sym_var_declaration] = STATE(15),
    [sym_type_specifier] = STATE(83),
    [sym_compound_statement] = STATE(4),
    [sym__statement] = STATE(4),
    [sym_selection_statement] = STATE(4),
    [sym_iteration_statement] = STATE(4),
    [sym_return_statement] = STATE(4),
    [sym_expression_statement] = STATE(4),
    [sym__expression] = STATE(32),
    [sym__simple_expression] = STATE(32),
    [sym_binary_expression] = STATE(32),
    [sym__factor] = STATE(32),
    [sym_call_expression] = STATE(32),
    [sym_assignment] = STATE(32),
    [sym_variable] = STATE(21),
    [sym_boolean_literal] = STATE(32),
    [aux_sym_compound_statement_repeat1] = STATE(15),
    [aux_sym_compound_statement_repeat2] = STATE(4),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_SEMI] = ACTIONS(9),
    [anon_sym_int] = ACTIONS(11),
    [anon_sym_void] = ACTIONS(11),
    [anon_sym_bool] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(29),
    [anon_sym_if] = ACTIONS(19),
    [anon_sym_while] = ACTIONS(21),
    [anon_sym_return] = ACTIONS(23),
    [sym_num_literal] = ACTIONS(25),
    [anon_sym_true] = ACTIONS(27),
    [anon_sym_false] = ACTIONS(27),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_while,
    ACTIONS(23), 1,
      anon_sym_return,
    ACTIONS(25), 1,
      sym_num_literal,
    ACTIONS(31), 1,
      anon_sym_RBRACE,
    STATE(21), 1,
      sym_variable,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(5), 7,
      sym_compound_statement,
      sym__statement,
      sym_selection_statement,
      sym_iteration_statement,
      sym_return_statement,
      sym_expression_statement,
      aux_sym_compound_statement_repeat2,
    STATE(32), 7,
      sym__expression,
      sym__simple_expression,
      sym_binary_expression,
      sym__factor,
      sym_call_expression,
      sym_assignment,
      sym_boolean_literal,
  [53] = 13,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(36), 1,
      anon_sym_SEMI,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(42), 1,
      anon_sym_LBRACE,
    ACTIONS(45), 1,
      anon_sym_RBRACE,
    ACTIONS(47), 1,
      anon_sym_if,
    ACTIONS(50), 1,
      anon_sym_while,
    ACTIONS(53), 1,
      anon_sym_return,
    ACTIONS(56), 1,
      sym_num_literal,
    STATE(21), 1,
      sym_variable,
    ACTIONS(59), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(5), 7,
      sym_compound_statement,
      sym__statement,
      sym_selection_statement,
      sym_iteration_statement,
      sym_return_statement,
      sym_expression_statement,
      aux_sym_compound_statement_repeat2,
    STATE(32), 7,
      sym__expression,
      sym__simple_expression,
      sym_binary_expression,
      sym__factor,
      sym_call_expression,
      sym_assignment,
      sym_boolean_literal,
  [106] = 13,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_while,
    ACTIONS(23), 1,
      anon_sym_return,
    ACTIONS(25), 1,
      sym_num_literal,
    ACTIONS(29), 1,
      anon_sym_RBRACE,
    STATE(21), 1,
      sym_variable,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(5), 7,
      sym_compound_statement,
      sym__statement,
      sym_selection_statement,
      sym_iteration_statement,
      sym_return_statement,
      sym_expression_statement,
      aux_sym_compound_statement_repeat2,
    STATE(32), 7,
      sym__expression,
      sym__simple_expression,
      sym_binary_expression,
      sym__factor,
      sym_call_expression,
      sym_assignment,
      sym_boolean_literal,
  [159] = 12,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_while,
    ACTIONS(23), 1,
      anon_sym_return,
    ACTIONS(25), 1,
      sym_num_literal,
    STATE(21), 1,
      sym_variable,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(54), 6,
      sym_compound_statement,
      sym__statement,
      sym_selection_statement,
      sym_iteration_statement,
      sym_return_statement,
      sym_expression_statement,
    STATE(32), 7,
      sym__expression,
      sym__simple_expression,
      sym_binary_expression,
      sym__factor,
      sym_call_expression,
      sym_assignment,
      sym_boolean_literal,
  [208] = 12,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_while,
    ACTIONS(23), 1,
      anon_sym_return,
    ACTIONS(25), 1,
      sym_num_literal,
    STATE(21), 1,
      sym_variable,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(48), 6,
      sym_compound_statement,
      sym__statement,
      sym_selection_statement,
      sym_iteration_statement,
      sym_return_statement,
      sym_expression_statement,
    STATE(32), 7,
      sym__expression,
      sym__simple_expression,
      sym_binary_expression,
      sym__factor,
      sym_call_expression,
      sym_assignment,
      sym_boolean_literal,
  [257] = 12,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_while,
    ACTIONS(23), 1,
      anon_sym_return,
    ACTIONS(25), 1,
      sym_num_literal,
    STATE(21), 1,
      sym_variable,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(49), 6,
      sym_compound_statement,
      sym__statement,
      sym_selection_statement,
      sym_iteration_statement,
      sym_return_statement,
      sym_expression_statement,
    STATE(32), 7,
      sym__expression,
      sym__simple_expression,
      sym_binary_expression,
      sym__factor,
      sym_call_expression,
      sym_assignment,
      sym_boolean_literal,
  [306] = 5,
    ACTIONS(62), 1,
      anon_sym_LBRACK,
    ACTIONS(66), 1,
      anon_sym_LPAREN,
    STATE(27), 1,
      sym_arg_list,
    ACTIONS(68), 3,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ,
    ACTIONS(64), 12,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [335] = 5,
    STATE(40), 1,
      sym_rel_op,
    STATE(45), 1,
      sym_add_op,
    STATE(47), 1,
      sym_mul_op,
    ACTIONS(72), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(70), 12,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [363] = 6,
    STATE(40), 1,
      sym_rel_op,
    STATE(45), 1,
      sym_add_op,
    STATE(47), 1,
      sym_mul_op,
    ACTIONS(72), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(74), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(70), 10,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
  [393] = 7,
    STATE(40), 1,
      sym_rel_op,
    STATE(45), 1,
      sym_add_op,
    STATE(47), 1,
      sym_mul_op,
    ACTIONS(72), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(74), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(76), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(70), 8,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [425] = 8,
    STATE(40), 1,
      sym_rel_op,
    STATE(45), 1,
      sym_add_op,
    STATE(47), 1,
      sym_mul_op,
    ACTIONS(74), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(76), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(80), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(78), 4,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(82), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [459] = 5,
    STATE(83), 1,
      sym_type_specifier,
    STATE(15), 2,
      sym_var_declaration,
      aux_sym_compound_statement_repeat1,
    ACTIONS(88), 3,
      anon_sym_int,
      anon_sym_void,
      anon_sym_bool,
    ACTIONS(86), 5,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_num_literal,
    ACTIONS(84), 6,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [487] = 2,
    ACTIONS(91), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_num_literal,
    ACTIONS(93), 10,
      anon_sym_int,
      anon_sym_void,
      anon_sym_bool,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
      anon_sym_return,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [508] = 10,
    ACTIONS(95), 1,
      anon_sym_COMMA,
    ACTIONS(97), 1,
      anon_sym_RPAREN,
    STATE(40), 1,
      sym_rel_op,
    STATE(45), 1,
      sym_add_op,
    STATE(47), 1,
      sym_mul_op,
    STATE(65), 1,
      aux_sym_arg_list_repeat1,
    ACTIONS(74), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(76), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(80), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(82), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [545] = 2,
    ACTIONS(99), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_num_literal,
    ACTIONS(101), 10,
      anon_sym_int,
      anon_sym_void,
      anon_sym_bool,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
      anon_sym_return,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [566] = 2,
    ACTIONS(103), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_num_literal,
    ACTIONS(105), 10,
      anon_sym_int,
      anon_sym_void,
      anon_sym_bool,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
      anon_sym_return,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [587] = 8,
    STATE(40), 1,
      sym_rel_op,
    STATE(45), 1,
      sym_add_op,
    STATE(47), 1,
      sym_mul_op,
    ACTIONS(74), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(76), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(80), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(107), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(82), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [619] = 3,
    ACTIONS(113), 1,
      anon_sym_EQ,
    ACTIONS(111), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(109), 12,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [641] = 2,
    ACTIONS(115), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_num_literal,
    ACTIONS(117), 9,
      anon_sym_int,
      anon_sym_void,
      anon_sym_bool,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [661] = 2,
    ACTIONS(121), 3,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ,
    ACTIONS(119), 12,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [681] = 2,
    ACTIONS(123), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_num_literal,
    ACTIONS(125), 9,
      anon_sym_int,
      anon_sym_void,
      anon_sym_bool,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [701] = 8,
    ACTIONS(127), 1,
      anon_sym_RBRACK,
    STATE(40), 1,
      sym_rel_op,
    STATE(45), 1,
      sym_add_op,
    STATE(47), 1,
      sym_mul_op,
    ACTIONS(74), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(76), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(80), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(82), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [732] = 2,
    ACTIONS(131), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(129), 12,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [751] = 2,
    ACTIONS(135), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(133), 12,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [770] = 7,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(137), 1,
      anon_sym_SEMI,
    ACTIONS(139), 1,
      sym_num_literal,
    STATE(21), 1,
      sym_variable,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(37), 7,
      sym__expression,
      sym__simple_expression,
      sym_binary_expression,
      sym__factor,
      sym_call_expression,
      sym_assignment,
      sym_boolean_literal,
  [799] = 2,
    ACTIONS(143), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(141), 12,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [818] = 2,
    ACTIONS(147), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(145), 12,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [837] = 7,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(149), 1,
      anon_sym_RPAREN,
    ACTIONS(151), 1,
      sym_num_literal,
    STATE(21), 1,
      sym_variable,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 7,
      sym__expression,
      sym__simple_expression,
      sym_binary_expression,
      sym__factor,
      sym_call_expression,
      sym_assignment,
      sym_boolean_literal,
  [866] = 8,
    ACTIONS(153), 1,
      anon_sym_SEMI,
    STATE(40), 1,
      sym_rel_op,
    STATE(45), 1,
      sym_add_op,
    STATE(47), 1,
      sym_mul_op,
    ACTIONS(74), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(76), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(80), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(82), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [897] = 8,
    ACTIONS(155), 1,
      anon_sym_RPAREN,
    STATE(40), 1,
      sym_rel_op,
    STATE(45), 1,
      sym_add_op,
    STATE(47), 1,
      sym_mul_op,
    ACTIONS(74), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(76), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(80), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(82), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [928] = 8,
    ACTIONS(157), 1,
      anon_sym_RPAREN,
    STATE(40), 1,
      sym_rel_op,
    STATE(45), 1,
      sym_add_op,
    STATE(47), 1,
      sym_mul_op,
    ACTIONS(74), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(76), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(80), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(82), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [959] = 8,
    ACTIONS(159), 1,
      anon_sym_RPAREN,
    STATE(40), 1,
      sym_rel_op,
    STATE(45), 1,
      sym_add_op,
    STATE(47), 1,
      sym_mul_op,
    ACTIONS(74), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(76), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(80), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(82), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [990] = 2,
    ACTIONS(163), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(161), 12,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1009] = 8,
    ACTIONS(165), 1,
      anon_sym_SEMI,
    STATE(40), 1,
      sym_rel_op,
    STATE(45), 1,
      sym_add_op,
    STATE(47), 1,
      sym_mul_op,
    ACTIONS(74), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(76), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(80), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(82), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1040] = 2,
    ACTIONS(169), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(167), 12,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1059] = 6,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(171), 1,
      sym_num_literal,
    STATE(21), 1,
      sym_variable,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(34), 7,
      sym__expression,
      sym__simple_expression,
      sym_binary_expression,
      sym__factor,
      sym_call_expression,
      sym_assignment,
      sym_boolean_literal,
  [1085] = 6,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(173), 1,
      sym_num_literal,
    STATE(21), 1,
      sym_variable,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(13), 7,
      sym__expression,
      sym__simple_expression,
      sym_binary_expression,
      sym__factor,
      sym_call_expression,
      sym_assignment,
      sym_boolean_literal,
  [1111] = 6,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(175), 1,
      sym_num_literal,
    STATE(21), 1,
      sym_variable,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 7,
      sym__expression,
      sym__simple_expression,
      sym_binary_expression,
      sym__factor,
      sym_call_expression,
      sym_assignment,
      sym_boolean_literal,
  [1137] = 6,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(177), 1,
      sym_num_literal,
    STATE(21), 1,
      sym_variable,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(35), 7,
      sym__expression,
      sym__simple_expression,
      sym_binary_expression,
      sym__factor,
      sym_call_expression,
      sym_assignment,
      sym_boolean_literal,
  [1163] = 6,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(179), 1,
      sym_num_literal,
    STATE(21), 1,
      sym_variable,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(33), 7,
      sym__expression,
      sym__simple_expression,
      sym_binary_expression,
      sym__factor,
      sym_call_expression,
      sym_assignment,
      sym_boolean_literal,
  [1189] = 6,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(181), 1,
      sym_num_literal,
    STATE(21), 1,
      sym_variable,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(14), 7,
      sym__expression,
      sym__simple_expression,
      sym_binary_expression,
      sym__factor,
      sym_call_expression,
      sym_assignment,
      sym_boolean_literal,
  [1215] = 6,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(183), 1,
      sym_num_literal,
    STATE(21), 1,
      sym_variable,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(12), 7,
      sym__expression,
      sym__simple_expression,
      sym_binary_expression,
      sym__factor,
      sym_call_expression,
      sym_assignment,
      sym_boolean_literal,
  [1241] = 6,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(185), 1,
      sym_num_literal,
    STATE(21), 1,
      sym_variable,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(25), 7,
      sym__expression,
      sym__simple_expression,
      sym_binary_expression,
      sym__factor,
      sym_call_expression,
      sym_assignment,
      sym_boolean_literal,
  [1267] = 6,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(187), 1,
      sym_num_literal,
    STATE(21), 1,
      sym_variable,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(11), 7,
      sym__expression,
      sym__simple_expression,
      sym_binary_expression,
      sym__factor,
      sym_call_expression,
      sym_assignment,
      sym_boolean_literal,
  [1293] = 2,
    ACTIONS(191), 5,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_num_literal,
    ACTIONS(189), 7,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
      anon_sym_return,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [1310] = 3,
    ACTIONS(197), 1,
      anon_sym_else,
    ACTIONS(195), 5,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_num_literal,
    ACTIONS(193), 6,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [1329] = 2,
    ACTIONS(201), 5,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_num_literal,
    ACTIONS(199), 7,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
      anon_sym_return,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [1346] = 2,
    ACTIONS(205), 5,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_num_literal,
    ACTIONS(203), 7,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
      anon_sym_return,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [1363] = 2,
    ACTIONS(209), 5,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_num_literal,
    ACTIONS(207), 7,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
      anon_sym_return,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [1380] = 2,
    ACTIONS(213), 5,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_num_literal,
    ACTIONS(211), 7,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
      anon_sym_return,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [1397] = 2,
    ACTIONS(217), 5,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_num_literal,
    ACTIONS(215), 7,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
      anon_sym_return,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [1414] = 4,
    ACTIONS(219), 1,
      ts_builtin_sym_end,
    STATE(84), 1,
      sym_type_specifier,
    ACTIONS(5), 3,
      anon_sym_int,
      anon_sym_void,
      anon_sym_bool,
    STATE(56), 4,
      sym__declaration,
      sym_var_declaration,
      sym_function_declaration,
      aux_sym_program_repeat1,
  [1432] = 4,
    ACTIONS(221), 1,
      ts_builtin_sym_end,
    STATE(84), 1,
      sym_type_specifier,
    ACTIONS(223), 3,
      anon_sym_int,
      anon_sym_void,
      anon_sym_bool,
    STATE(56), 4,
      sym__declaration,
      sym_var_declaration,
      sym_function_declaration,
      aux_sym_program_repeat1,
  [1450] = 4,
    ACTIONS(226), 1,
      anon_sym_RPAREN,
    STATE(68), 1,
      sym_param,
    STATE(75), 1,
      sym_type_specifier,
    ACTIONS(5), 3,
      anon_sym_int,
      anon_sym_void,
      anon_sym_bool,
  [1465] = 2,
    ACTIONS(230), 2,
      anon_sym_LPAREN,
      sym_num_literal,
    ACTIONS(228), 3,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [1475] = 2,
    ACTIONS(234), 2,
      anon_sym_LPAREN,
      sym_num_literal,
    ACTIONS(232), 3,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [1485] = 3,
    STATE(71), 1,
      sym_param,
    STATE(75), 1,
      sym_type_specifier,
    ACTIONS(5), 3,
      anon_sym_int,
      anon_sym_void,
      anon_sym_bool,
  [1497] = 2,
    ACTIONS(238), 2,
      anon_sym_LPAREN,
      sym_num_literal,
    ACTIONS(236), 3,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [1507] = 4,
    ACTIONS(240), 1,
      anon_sym_LBRACK,
    ACTIONS(242), 1,
      anon_sym_SEMI,
    ACTIONS(244), 1,
      anon_sym_LPAREN,
    STATE(72), 1,
      sym_param_list,
  [1520] = 1,
    ACTIONS(246), 4,
      ts_builtin_sym_end,
      anon_sym_int,
      anon_sym_void,
      anon_sym_bool,
  [1527] = 3,
    ACTIONS(107), 1,
      anon_sym_RPAREN,
    ACTIONS(248), 1,
      anon_sym_COMMA,
    STATE(64), 1,
      aux_sym_arg_list_repeat1,
  [1537] = 3,
    ACTIONS(95), 1,
      anon_sym_COMMA,
    ACTIONS(251), 1,
      anon_sym_RPAREN,
    STATE(64), 1,
      aux_sym_arg_list_repeat1,
  [1547] = 3,
    ACTIONS(253), 1,
      anon_sym_COMMA,
    ACTIONS(255), 1,
      anon_sym_RPAREN,
    STATE(69), 1,
      aux_sym_param_list_repeat1,
  [1557] = 2,
    ACTIONS(257), 1,
      anon_sym_LBRACK,
    ACTIONS(259), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1565] = 3,
    ACTIONS(253), 1,
      anon_sym_COMMA,
    ACTIONS(261), 1,
      anon_sym_RPAREN,
    STATE(66), 1,
      aux_sym_param_list_repeat1,
  [1575] = 3,
    ACTIONS(263), 1,
      anon_sym_COMMA,
    ACTIONS(266), 1,
      anon_sym_RPAREN,
    STATE(69), 1,
      aux_sym_param_list_repeat1,
  [1585] = 1,
    ACTIONS(268), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1590] = 1,
    ACTIONS(266), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1595] = 2,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    STATE(63), 1,
      sym_compound_statement,
  [1602] = 2,
    ACTIONS(240), 1,
      anon_sym_LBRACK,
    ACTIONS(242), 1,
      anon_sym_SEMI,
  [1609] = 1,
    ACTIONS(270), 1,
      anon_sym_LBRACE,
  [1613] = 1,
    ACTIONS(272), 1,
      sym_identifier,
  [1617] = 1,
    ACTIONS(274), 1,
      sym_num_literal,
  [1621] = 1,
    ACTIONS(276), 1,
      anon_sym_LBRACE,
  [1625] = 1,
    ACTIONS(278), 1,
      anon_sym_RBRACK,
  [1629] = 1,
    ACTIONS(280), 1,
      anon_sym_SEMI,
  [1633] = 1,
    ACTIONS(282), 1,
      anon_sym_LBRACE,
  [1637] = 1,
    ACTIONS(284), 1,
      anon_sym_LPAREN,
  [1641] = 1,
    ACTIONS(286), 1,
      anon_sym_LPAREN,
  [1645] = 1,
    ACTIONS(288), 1,
      sym_identifier,
  [1649] = 1,
    ACTIONS(290), 1,
      sym_identifier,
  [1653] = 1,
    ACTIONS(292), 1,
      anon_sym_RBRACK,
  [1657] = 1,
    ACTIONS(294), 1,
      ts_builtin_sym_end,
  [1661] = 1,
    ACTIONS(296), 1,
      sym_identifier,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 53,
  [SMALL_STATE(6)] = 106,
  [SMALL_STATE(7)] = 159,
  [SMALL_STATE(8)] = 208,
  [SMALL_STATE(9)] = 257,
  [SMALL_STATE(10)] = 306,
  [SMALL_STATE(11)] = 335,
  [SMALL_STATE(12)] = 363,
  [SMALL_STATE(13)] = 393,
  [SMALL_STATE(14)] = 425,
  [SMALL_STATE(15)] = 459,
  [SMALL_STATE(16)] = 487,
  [SMALL_STATE(17)] = 508,
  [SMALL_STATE(18)] = 545,
  [SMALL_STATE(19)] = 566,
  [SMALL_STATE(20)] = 587,
  [SMALL_STATE(21)] = 619,
  [SMALL_STATE(22)] = 641,
  [SMALL_STATE(23)] = 661,
  [SMALL_STATE(24)] = 681,
  [SMALL_STATE(25)] = 701,
  [SMALL_STATE(26)] = 732,
  [SMALL_STATE(27)] = 751,
  [SMALL_STATE(28)] = 770,
  [SMALL_STATE(29)] = 799,
  [SMALL_STATE(30)] = 818,
  [SMALL_STATE(31)] = 837,
  [SMALL_STATE(32)] = 866,
  [SMALL_STATE(33)] = 897,
  [SMALL_STATE(34)] = 928,
  [SMALL_STATE(35)] = 959,
  [SMALL_STATE(36)] = 990,
  [SMALL_STATE(37)] = 1009,
  [SMALL_STATE(38)] = 1040,
  [SMALL_STATE(39)] = 1059,
  [SMALL_STATE(40)] = 1085,
  [SMALL_STATE(41)] = 1111,
  [SMALL_STATE(42)] = 1137,
  [SMALL_STATE(43)] = 1163,
  [SMALL_STATE(44)] = 1189,
  [SMALL_STATE(45)] = 1215,
  [SMALL_STATE(46)] = 1241,
  [SMALL_STATE(47)] = 1267,
  [SMALL_STATE(48)] = 1293,
  [SMALL_STATE(49)] = 1310,
  [SMALL_STATE(50)] = 1329,
  [SMALL_STATE(51)] = 1346,
  [SMALL_STATE(52)] = 1363,
  [SMALL_STATE(53)] = 1380,
  [SMALL_STATE(54)] = 1397,
  [SMALL_STATE(55)] = 1414,
  [SMALL_STATE(56)] = 1432,
  [SMALL_STATE(57)] = 1450,
  [SMALL_STATE(58)] = 1465,
  [SMALL_STATE(59)] = 1475,
  [SMALL_STATE(60)] = 1485,
  [SMALL_STATE(61)] = 1497,
  [SMALL_STATE(62)] = 1507,
  [SMALL_STATE(63)] = 1520,
  [SMALL_STATE(64)] = 1527,
  [SMALL_STATE(65)] = 1537,
  [SMALL_STATE(66)] = 1547,
  [SMALL_STATE(67)] = 1557,
  [SMALL_STATE(68)] = 1565,
  [SMALL_STATE(69)] = 1575,
  [SMALL_STATE(70)] = 1585,
  [SMALL_STATE(71)] = 1590,
  [SMALL_STATE(72)] = 1595,
  [SMALL_STATE(73)] = 1602,
  [SMALL_STATE(74)] = 1609,
  [SMALL_STATE(75)] = 1613,
  [SMALL_STATE(76)] = 1617,
  [SMALL_STATE(77)] = 1621,
  [SMALL_STATE(78)] = 1625,
  [SMALL_STATE(79)] = 1629,
  [SMALL_STATE(80)] = 1633,
  [SMALL_STATE(81)] = 1637,
  [SMALL_STATE(82)] = 1641,
  [SMALL_STATE(83)] = 1645,
  [SMALL_STATE(84)] = 1649,
  [SMALL_STATE(85)] = 1653,
  [SMALL_STATE(86)] = 1657,
  [SMALL_STATE(87)] = 1661,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_compound_statement_repeat2, 2), SHIFT_REPEAT(10),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_statement_repeat2, 2), SHIFT_REPEAT(52),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_statement_repeat2, 2), SHIFT_REPEAT(42),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_statement_repeat2, 2), SHIFT_REPEAT(2),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_compound_statement_repeat2, 2),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_compound_statement_repeat2, 2), SHIFT_REPEAT(81),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_compound_statement_repeat2, 2), SHIFT_REPEAT(82),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_compound_statement_repeat2, 2), SHIFT_REPEAT(28),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_statement_repeat2, 2), SHIFT_REPEAT(32),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_compound_statement_repeat2, 2), SHIFT_REPEAT(30),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 1),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 1),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, .production_id = 2),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, .production_id = 2),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, .production_id = 3),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_compound_statement_repeat1, 2),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_compound_statement_repeat1, 2),
  [88] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_compound_statement_repeat1, 2), SHIFT_REPEAT(87),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound_statement, 3),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compound_statement, 3),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound_statement, 4),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compound_statement, 4),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound_statement, 2),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compound_statement, 2),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arg_list_repeat1, 2),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__factor, 1),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__factor, 1),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_declaration, 3, .production_id = 1),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var_declaration, 3, .production_id = 1),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 4),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 4),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_declaration, 6, .production_id = 1),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var_declaration, 6, .production_id = 1),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__factor, 3),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__factor, 3),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 2),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_expression, 2),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_list, 4),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg_list, 4),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean_literal, 1),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_list, 2),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg_list, 2),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_list, 3),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg_list, 3),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_iteration_statement, 5),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_iteration_statement, 5),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_selection_statement, 5),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selection_statement, 5),
  [197] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_statement, 2),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_statement, 2),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 3),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 3),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_statement, 1),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_statement, 1),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 2),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 2),
  [215] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_selection_statement, 7),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selection_statement, 7),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2),
  [223] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(87),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_add_op, 1),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_add_op, 1),
  [232] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mul_op, 1),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mul_op, 1),
  [236] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rel_op, 1),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rel_op, 1),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 4, .production_id = 1),
  [248] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arg_list_repeat1, 2), SHIFT_REPEAT(41),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 2),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [263] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_param_list_repeat1, 2), SHIFT_REPEAT(60),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_param_list_repeat1, 2),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 4),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_list, 3),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_list, 2),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_list, 4),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [294] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [296] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_specifier, 1),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_cm(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const unsigned short *)ts_parse_table,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .symbol_names = ts_symbol_names,
    .public_symbol_map = ts_symbol_map,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .field_count = FIELD_COUNT,
    .field_names = ts_field_names,
    .field_map_slices = (const TSFieldMapSlice *)ts_field_map_slices,
    .field_map_entries = (const TSFieldMapEntry *)ts_field_map_entries,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
