#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 11
#define STATE_COUNT 87
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 58
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 7

enum {
  sym_identifier = 1,
  anon_sym_LBRACK = 2,
  anon_sym_RBRACK = 3,
  anon_sym_SEMI = 4,
  anon_sym_int = 5,
  anon_sym_void = 6,
  anon_sym_bool = 7,
  anon_sym_LPAREN = 8,
  anon_sym_COMMA = 9,
  anon_sym_RPAREN = 10,
  anon_sym_LBRACE = 11,
  anon_sym_RBRACE = 12,
  anon_sym_if = 13,
  anon_sym_else = 14,
  anon_sym_while = 15,
  anon_sym_return = 16,
  anon_sym_GT = 17,
  anon_sym_GT_EQ = 18,
  anon_sym_LT = 19,
  anon_sym_LT_EQ = 20,
  anon_sym_EQ_EQ = 21,
  anon_sym_BANG_EQ = 22,
  anon_sym_PLUS = 23,
  anon_sym_DASH = 24,
  anon_sym_STAR = 25,
  anon_sym_SLASH = 26,
  anon_sym_EQ = 27,
  sym_num_literal = 28,
  sym_program = 29,
  sym__declaration = 30,
  sym_var_declaration = 31,
  sym_type_specifier = 32,
  sym_function_declaration = 33,
  sym_param_list = 34,
  sym_param = 35,
  sym_compound_statement = 36,
  sym__statement = 37,
  sym_selection_statement = 38,
  sym_iteration_statement = 39,
  sym_return_statement = 40,
  sym_expression_statement = 41,
  sym__expression = 42,
  sym__simple_expression = 43,
  sym_binary_expression = 44,
  sym_rel_op = 45,
  sym_add_op = 46,
  sym_mul_op = 47,
  sym__factor = 48,
  sym_call_expression = 49,
  sym_arg_list = 50,
  sym_assignment = 51,
  sym_variable = 52,
  aux_sym_program_repeat1 = 53,
  aux_sym_param_list_repeat1 = 54,
  aux_sym_compound_statement_repeat1 = 55,
  aux_sym_compound_statement_repeat2 = 56,
  aux_sym_arg_list_repeat1 = 57,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_SEMI] = ";",
  [anon_sym_int] = "int",
  [anon_sym_void] = "void",
  [anon_sym_bool] = "bool",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_while] = "while",
  [anon_sym_return] = "return",
  [anon_sym_GT] = ">",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT] = "<",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_EQ] = "=",
  [sym_num_literal] = "num_literal",
  [sym_program] = "program",
  [sym__declaration] = "_declaration",
  [sym_var_declaration] = "var_declaration",
  [sym_type_specifier] = "type_specifier",
  [sym_function_declaration] = "function_declaration",
  [sym_param_list] = "param_list",
  [sym_param] = "param",
  [sym_compound_statement] = "compound_statement",
  [sym__statement] = "_statement",
  [sym_selection_statement] = "selection_statement",
  [sym_iteration_statement] = "iteration_statement",
  [sym_return_statement] = "return_statement",
  [sym_expression_statement] = "expression_statement",
  [sym__expression] = "_expression",
  [sym__simple_expression] = "_simple_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_rel_op] = "rel_op",
  [sym_add_op] = "add_op",
  [sym_mul_op] = "mul_op",
  [sym__factor] = "_factor",
  [sym_call_expression] = "call_expression",
  [sym_arg_list] = "arg_list",
  [sym_assignment] = "assignment",
  [sym_variable] = "variable",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_param_list_repeat1] = "param_list_repeat1",
  [aux_sym_compound_statement_repeat1] = "compound_statement_repeat1",
  [aux_sym_compound_statement_repeat2] = "compound_statement_repeat2",
  [aux_sym_arg_list_repeat1] = "arg_list_repeat1",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_int] = anon_sym_int,
  [anon_sym_void] = anon_sym_void,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_num_literal] = sym_num_literal,
  [sym_program] = sym_program,
  [sym__declaration] = sym__declaration,
  [sym_var_declaration] = sym_var_declaration,
  [sym_type_specifier] = sym_type_specifier,
  [sym_function_declaration] = sym_function_declaration,
  [sym_param_list] = sym_param_list,
  [sym_param] = sym_param,
  [sym_compound_statement] = sym_compound_statement,
  [sym__statement] = sym__statement,
  [sym_selection_statement] = sym_selection_statement,
  [sym_iteration_statement] = sym_iteration_statement,
  [sym_return_statement] = sym_return_statement,
  [sym_expression_statement] = sym_expression_statement,
  [sym__expression] = sym__expression,
  [sym__simple_expression] = sym__simple_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_rel_op] = sym_rel_op,
  [sym_add_op] = sym_add_op,
  [sym_mul_op] = sym_mul_op,
  [sym__factor] = sym__factor,
  [sym_call_expression] = sym_call_expression,
  [sym_arg_list] = sym_arg_list,
  [sym_assignment] = sym_assignment,
  [sym_variable] = sym_variable,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_param_list_repeat1] = aux_sym_param_list_repeat1,
  [aux_sym_compound_statement_repeat1] = aux_sym_compound_statement_repeat1,
  [aux_sym_compound_statement_repeat2] = aux_sym_compound_statement_repeat2,
  [aux_sym_arg_list_repeat1] = aux_sym_arg_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_void] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_num_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym__declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_var_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_type_specifier] = {
    .visible = true,
    .named = true,
  },
  [sym_function_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_param_list] = {
    .visible = true,
    .named = true,
  },
  [sym_param] = {
    .visible = true,
    .named = true,
  },
  [sym_compound_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_selection_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_iteration_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__simple_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_rel_op] = {
    .visible = true,
    .named = true,
  },
  [sym_add_op] = {
    .visible = true,
    .named = true,
  },
  [sym_mul_op] = {
    .visible = true,
    .named = true,
  },
  [sym__factor] = {
    .visible = false,
    .named = true,
  },
  [sym_call_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_arg_list] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_param_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_compound_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_compound_statement_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arg_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_left = 1,
  field_op = 2,
  field_right = 3,
};

static const char *ts_field_names[] = {
  [0] = NULL,
  [field_left] = "left",
  [field_op] = "op",
  [field_right] = "right",
};

static const TSFieldMapSlice ts_field_map_slices[3] = {
  [1] = {.index = 0, .length = 3},
  [2] = {.index = 3, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_left, 0},
    {field_op, 1},
    {field_right, 2},
  [3] =
    {field_left, 0},
    {field_right, 2},
};

static TSSymbol ts_alias_sequences[3][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(2);
      if (lookahead == '!') ADVANCE(1);
      if (lookahead == '(') ADVANCE(6);
      if (lookahead == ')') ADVANCE(8);
      if (lookahead == '*') ADVANCE(19);
      if (lookahead == '+') ADVANCE(17);
      if (lookahead == ',') ADVANCE(7);
      if (lookahead == '-') ADVANCE(18);
      if (lookahead == '/') ADVANCE(20);
      if (lookahead == ';') ADVANCE(5);
      if (lookahead == '<') ADVANCE(13);
      if (lookahead == '=') ADVANCE(21);
      if (lookahead == '>') ADVANCE(11);
      if (lookahead == '[') ADVANCE(3);
      if (lookahead == ']') ADVANCE(4);
      if (lookahead == '{') ADVANCE(9);
      if (lookahead == '}') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 1:
      if (lookahead == '=') ADVANCE(16);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(12);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(14);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(15);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_num_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'b') ADVANCE(1);
      if (lookahead == 'e') ADVANCE(2);
      if (lookahead == 'i') ADVANCE(3);
      if (lookahead == 'r') ADVANCE(4);
      if (lookahead == 'v') ADVANCE(5);
      if (lookahead == 'w') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'o') ADVANCE(7);
      END_STATE();
    case 2:
      if (lookahead == 'l') ADVANCE(8);
      END_STATE();
    case 3:
      if (lookahead == 'f') ADVANCE(9);
      if (lookahead == 'n') ADVANCE(10);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 5:
      if (lookahead == 'o') ADVANCE(12);
      END_STATE();
    case 6:
      if (lookahead == 'h') ADVANCE(13);
      END_STATE();
    case 7:
      if (lookahead == 'o') ADVANCE(14);
      END_STATE();
    case 8:
      if (lookahead == 's') ADVANCE(15);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 10:
      if (lookahead == 't') ADVANCE(16);
      END_STATE();
    case 11:
      if (lookahead == 't') ADVANCE(17);
      END_STATE();
    case 12:
      if (lookahead == 'i') ADVANCE(18);
      END_STATE();
    case 13:
      if (lookahead == 'i') ADVANCE(19);
      END_STATE();
    case 14:
      if (lookahead == 'l') ADVANCE(20);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_int);
      END_STATE();
    case 17:
      if (lookahead == 'u') ADVANCE(22);
      END_STATE();
    case 18:
      if (lookahead == 'd') ADVANCE(23);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(24);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_bool);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 22:
      if (lookahead == 'r') ADVANCE(25);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_void);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 25:
      if (lookahead == 'n') ADVANCE(27);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_while);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_int] = ACTIONS(1),
    [anon_sym_void] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_num_literal] = ACTIONS(1),
  },
  [1] = {
    [sym_program] = STATE(85),
    [sym__declaration] = STATE(54),
    [sym_var_declaration] = STATE(54),
    [sym_type_specifier] = STATE(83),
    [sym_function_declaration] = STATE(54),
    [aux_sym_program_repeat1] = STATE(54),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_int] = ACTIONS(5),
    [anon_sym_void] = ACTIONS(5),
    [anon_sym_bool] = ACTIONS(5),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 15,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_RBRACE,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_while,
    ACTIONS(23), 1,
      anon_sym_return,
    ACTIONS(25), 1,
      sym_num_literal,
    STATE(18), 1,
      sym_variable,
    STATE(82), 1,
      sym_type_specifier,
    STATE(19), 2,
      sym_var_declaration,
      aux_sym_compound_statement_repeat1,
    ACTIONS(11), 3,
      anon_sym_int,
      anon_sym_void,
      anon_sym_bool,
    STATE(29), 6,
      sym__expression,
      sym__simple_expression,
      sym_binary_expression,
      sym__factor,
      sym_call_expression,
      sym_assignment,
    STATE(6), 7,
      sym_compound_statement,
      sym__statement,
      sym_selection_statement,
      sym_iteration_statement,
      sym_return_statement,
      sym_expression_statement,
      aux_sym_compound_statement_repeat2,
  [60] = 15,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_while,
    ACTIONS(23), 1,
      anon_sym_return,
    ACTIONS(25), 1,
      sym_num_literal,
    ACTIONS(27), 1,
      anon_sym_RBRACE,
    STATE(18), 1,
      sym_variable,
    STATE(82), 1,
      sym_type_specifier,
    STATE(2), 2,
      sym_var_declaration,
      aux_sym_compound_statement_repeat1,
    ACTIONS(11), 3,
      anon_sym_int,
      anon_sym_void,
      anon_sym_bool,
    STATE(29), 6,
      sym__expression,
      sym__simple_expression,
      sym_binary_expression,
      sym__factor,
      sym_call_expression,
      sym_assignment,
    STATE(5), 7,
      sym_compound_statement,
      sym__statement,
      sym_selection_statement,
      sym_iteration_statement,
      sym_return_statement,
      sym_expression_statement,
      aux_sym_compound_statement_repeat2,
  [120] = 12,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(32), 1,
      anon_sym_SEMI,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(38), 1,
      anon_sym_LBRACE,
    ACTIONS(41), 1,
      anon_sym_RBRACE,
    ACTIONS(43), 1,
      anon_sym_if,
    ACTIONS(46), 1,
      anon_sym_while,
    ACTIONS(49), 1,
      anon_sym_return,
    ACTIONS(52), 1,
      sym_num_literal,
    STATE(18), 1,
      sym_variable,
    STATE(29), 6,
      sym__expression,
      sym__simple_expression,
      sym_binary_expression,
      sym__factor,
      sym_call_expression,
      sym_assignment,
    STATE(4), 7,
      sym_compound_statement,
      sym__statement,
      sym_selection_statement,
      sym_iteration_statement,
      sym_return_statement,
      sym_expression_statement,
      aux_sym_compound_statement_repeat2,
  [168] = 12,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_RBRACE,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_while,
    ACTIONS(23), 1,
      anon_sym_return,
    ACTIONS(25), 1,
      sym_num_literal,
    STATE(18), 1,
      sym_variable,
    STATE(29), 6,
      sym__expression,
      sym__simple_expression,
      sym_binary_expression,
      sym__factor,
      sym_call_expression,
      sym_assignment,
    STATE(4), 7,
      sym_compound_statement,
      sym__statement,
      sym_selection_statement,
      sym_iteration_statement,
      sym_return_statement,
      sym_expression_statement,
      aux_sym_compound_statement_repeat2,
  [216] = 12,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_while,
    ACTIONS(23), 1,
      anon_sym_return,
    ACTIONS(25), 1,
      sym_num_literal,
    ACTIONS(55), 1,
      anon_sym_RBRACE,
    STATE(18), 1,
      sym_variable,
    STATE(29), 6,
      sym__expression,
      sym__simple_expression,
      sym_binary_expression,
      sym__factor,
      sym_call_expression,
      sym_assignment,
    STATE(4), 7,
      sym_compound_statement,
      sym__statement,
      sym_selection_statement,
      sym_iteration_statement,
      sym_return_statement,
      sym_expression_statement,
      aux_sym_compound_statement_repeat2,
  [264] = 11,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_while,
    ACTIONS(23), 1,
      anon_sym_return,
    ACTIONS(25), 1,
      sym_num_literal,
    STATE(18), 1,
      sym_variable,
    STATE(29), 6,
      sym__expression,
      sym__simple_expression,
      sym_binary_expression,
      sym__factor,
      sym_call_expression,
      sym_assignment,
    STATE(40), 6,
      sym_compound_statement,
      sym__statement,
      sym_selection_statement,
      sym_iteration_statement,
      sym_return_statement,
      sym_expression_statement,
  [308] = 11,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_while,
    ACTIONS(23), 1,
      anon_sym_return,
    ACTIONS(25), 1,
      sym_num_literal,
    STATE(18), 1,
      sym_variable,
    STATE(29), 6,
      sym__expression,
      sym__simple_expression,
      sym_binary_expression,
      sym__factor,
      sym_call_expression,
      sym_assignment,
    STATE(47), 6,
      sym_compound_statement,
      sym__statement,
      sym_selection_statement,
      sym_iteration_statement,
      sym_return_statement,
      sym_expression_statement,
  [352] = 11,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_while,
    ACTIONS(23), 1,
      anon_sym_return,
    ACTIONS(25), 1,
      sym_num_literal,
    STATE(18), 1,
      sym_variable,
    STATE(29), 6,
      sym__expression,
      sym__simple_expression,
      sym_binary_expression,
      sym__factor,
      sym_call_expression,
      sym_assignment,
    STATE(50), 6,
      sym_compound_statement,
      sym__statement,
      sym_selection_statement,
      sym_iteration_statement,
      sym_return_statement,
      sym_expression_statement,
  [396] = 5,
    ACTIONS(57), 1,
      anon_sym_LBRACK,
    ACTIONS(61), 1,
      anon_sym_LPAREN,
    STATE(20), 1,
      sym_arg_list,
    ACTIONS(63), 3,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ,
    ACTIONS(59), 12,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [425] = 8,
    STATE(39), 1,
      sym_mul_op,
    STATE(52), 1,
      sym_add_op,
    STATE(53), 1,
      sym_rel_op,
    ACTIONS(67), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(71), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(73), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(65), 4,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(69), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [459] = 5,
    STATE(39), 1,
      sym_mul_op,
    STATE(52), 1,
      sym_add_op,
    STATE(53), 1,
      sym_rel_op,
    ACTIONS(77), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(75), 12,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [487] = 6,
    STATE(39), 1,
      sym_mul_op,
    STATE(52), 1,
      sym_add_op,
    STATE(53), 1,
      sym_rel_op,
    ACTIONS(73), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(77), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(75), 10,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
  [517] = 7,
    STATE(39), 1,
      sym_mul_op,
    STATE(52), 1,
      sym_add_op,
    STATE(53), 1,
      sym_rel_op,
    ACTIONS(71), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(73), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(77), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(75), 8,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [549] = 10,
    ACTIONS(79), 1,
      anon_sym_COMMA,
    ACTIONS(81), 1,
      anon_sym_RPAREN,
    STATE(39), 1,
      sym_mul_op,
    STATE(52), 1,
      sym_add_op,
    STATE(53), 1,
      sym_rel_op,
    STATE(63), 1,
      aux_sym_arg_list_repeat1,
    ACTIONS(67), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(71), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(73), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(69), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [586] = 8,
    STATE(39), 1,
      sym_mul_op,
    STATE(52), 1,
      sym_add_op,
    STATE(53), 1,
      sym_rel_op,
    ACTIONS(67), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(71), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(73), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(83), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(69), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [618] = 2,
    ACTIONS(87), 3,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ,
    ACTIONS(85), 12,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [638] = 3,
    ACTIONS(93), 1,
      anon_sym_EQ,
    ACTIONS(91), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(89), 12,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [660] = 5,
    STATE(82), 1,
      sym_type_specifier,
    STATE(19), 2,
      sym_var_declaration,
      aux_sym_compound_statement_repeat1,
    ACTIONS(99), 3,
      anon_sym_int,
      anon_sym_void,
      anon_sym_bool,
    ACTIONS(95), 4,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      sym_identifier,
    ACTIONS(97), 5,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_num_literal,
  [686] = 2,
    ACTIONS(104), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(102), 12,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [705] = 2,
    ACTIONS(108), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(106), 12,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [724] = 8,
    ACTIONS(110), 1,
      anon_sym_RPAREN,
    STATE(39), 1,
      sym_mul_op,
    STATE(52), 1,
      sym_add_op,
    STATE(53), 1,
      sym_rel_op,
    ACTIONS(67), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(71), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(73), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(69), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [755] = 2,
    ACTIONS(114), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(112), 12,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [774] = 8,
    ACTIONS(116), 1,
      anon_sym_RPAREN,
    STATE(39), 1,
      sym_mul_op,
    STATE(52), 1,
      sym_add_op,
    STATE(53), 1,
      sym_rel_op,
    ACTIONS(67), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(71), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(73), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(69), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [805] = 2,
    ACTIONS(118), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_num_literal,
    ACTIONS(120), 8,
      anon_sym_int,
      anon_sym_void,
      anon_sym_bool,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
      anon_sym_return,
      sym_identifier,
  [824] = 2,
    ACTIONS(122), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_num_literal,
    ACTIONS(124), 8,
      anon_sym_int,
      anon_sym_void,
      anon_sym_bool,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
      anon_sym_return,
      sym_identifier,
  [843] = 8,
    ACTIONS(126), 1,
      anon_sym_RPAREN,
    STATE(39), 1,
      sym_mul_op,
    STATE(52), 1,
      sym_add_op,
    STATE(53), 1,
      sym_rel_op,
    ACTIONS(67), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(71), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(73), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(69), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [874] = 8,
    ACTIONS(128), 1,
      anon_sym_RBRACK,
    STATE(39), 1,
      sym_mul_op,
    STATE(52), 1,
      sym_add_op,
    STATE(53), 1,
      sym_rel_op,
    ACTIONS(67), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(71), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(73), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(69), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [905] = 8,
    ACTIONS(130), 1,
      anon_sym_SEMI,
    STATE(39), 1,
      sym_mul_op,
    STATE(52), 1,
      sym_add_op,
    STATE(53), 1,
      sym_rel_op,
    ACTIONS(67), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(71), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(73), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(69), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [936] = 2,
    ACTIONS(134), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(132), 12,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [955] = 2,
    ACTIONS(136), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_num_literal,
    ACTIONS(138), 8,
      anon_sym_int,
      anon_sym_void,
      anon_sym_bool,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
      anon_sym_return,
      sym_identifier,
  [974] = 8,
    ACTIONS(140), 1,
      anon_sym_SEMI,
    STATE(39), 1,
      sym_mul_op,
    STATE(52), 1,
      sym_add_op,
    STATE(53), 1,
      sym_rel_op,
    ACTIONS(67), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(71), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(73), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(69), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1005] = 2,
    ACTIONS(144), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(142), 12,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1024] = 2,
    ACTIONS(146), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_num_literal,
    ACTIONS(148), 7,
      anon_sym_int,
      anon_sym_void,
      anon_sym_bool,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      sym_identifier,
  [1042] = 2,
    ACTIONS(150), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_num_literal,
    ACTIONS(152), 7,
      anon_sym_int,
      anon_sym_void,
      anon_sym_bool,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      sym_identifier,
  [1060] = 6,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      sym_identifier,
    ACTIONS(156), 1,
      anon_sym_SEMI,
    ACTIONS(158), 1,
      sym_num_literal,
    STATE(18), 1,
      sym_variable,
    STATE(32), 6,
      sym__expression,
      sym__simple_expression,
      sym_binary_expression,
      sym__factor,
      sym_call_expression,
      sym_assignment,
  [1084] = 6,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      sym_identifier,
    ACTIONS(160), 1,
      anon_sym_RPAREN,
    ACTIONS(162), 1,
      sym_num_literal,
    STATE(18), 1,
      sym_variable,
    STATE(15), 6,
      sym__expression,
      sym__simple_expression,
      sym_binary_expression,
      sym__factor,
      sym_call_expression,
      sym_assignment,
  [1108] = 5,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      sym_identifier,
    ACTIONS(164), 1,
      sym_num_literal,
    STATE(18), 1,
      sym_variable,
    STATE(24), 6,
      sym__expression,
      sym__simple_expression,
      sym_binary_expression,
      sym__factor,
      sym_call_expression,
      sym_assignment,
  [1129] = 5,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      sym_identifier,
    ACTIONS(166), 1,
      sym_num_literal,
    STATE(18), 1,
      sym_variable,
    STATE(12), 6,
      sym__expression,
      sym__simple_expression,
      sym_binary_expression,
      sym__factor,
      sym_call_expression,
      sym_assignment,
  [1150] = 2,
    ACTIONS(168), 5,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
      anon_sym_return,
      sym_identifier,
    ACTIONS(170), 5,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_num_literal,
  [1165] = 5,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      sym_identifier,
    ACTIONS(172), 1,
      sym_num_literal,
    STATE(18), 1,
      sym_variable,
    STATE(16), 6,
      sym__expression,
      sym__simple_expression,
      sym_binary_expression,
      sym__factor,
      sym_call_expression,
      sym_assignment,
  [1186] = 5,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      sym_identifier,
    ACTIONS(174), 1,
      sym_num_literal,
    STATE(18), 1,
      sym_variable,
    STATE(22), 6,
      sym__expression,
      sym__simple_expression,
      sym_binary_expression,
      sym__factor,
      sym_call_expression,
      sym_assignment,
  [1207] = 2,
    ACTIONS(176), 5,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
      anon_sym_return,
      sym_identifier,
    ACTIONS(178), 5,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_num_literal,
  [1222] = 2,
    ACTIONS(180), 5,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
      anon_sym_return,
      sym_identifier,
    ACTIONS(182), 5,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_num_literal,
  [1237] = 5,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      sym_identifier,
    ACTIONS(184), 1,
      sym_num_literal,
    STATE(18), 1,
      sym_variable,
    STATE(28), 6,
      sym__expression,
      sym__simple_expression,
      sym_binary_expression,
      sym__factor,
      sym_call_expression,
      sym_assignment,
  [1258] = 2,
    ACTIONS(186), 5,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
      anon_sym_return,
      sym_identifier,
    ACTIONS(188), 5,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_num_literal,
  [1273] = 2,
    ACTIONS(190), 5,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
      anon_sym_return,
      sym_identifier,
    ACTIONS(192), 5,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_num_literal,
  [1288] = 5,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      sym_identifier,
    ACTIONS(194), 1,
      sym_num_literal,
    STATE(18), 1,
      sym_variable,
    STATE(27), 6,
      sym__expression,
      sym__simple_expression,
      sym_binary_expression,
      sym__factor,
      sym_call_expression,
      sym_assignment,
  [1309] = 2,
    ACTIONS(196), 5,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
      anon_sym_return,
      sym_identifier,
    ACTIONS(198), 5,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_num_literal,
  [1324] = 3,
    ACTIONS(204), 1,
      anon_sym_else,
    ACTIONS(200), 4,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      sym_identifier,
    ACTIONS(202), 5,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_num_literal,
  [1341] = 5,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      sym_identifier,
    ACTIONS(206), 1,
      sym_num_literal,
    STATE(18), 1,
      sym_variable,
    STATE(11), 6,
      sym__expression,
      sym__simple_expression,
      sym_binary_expression,
      sym__factor,
      sym_call_expression,
      sym_assignment,
  [1362] = 5,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      sym_identifier,
    ACTIONS(208), 1,
      sym_num_literal,
    STATE(18), 1,
      sym_variable,
    STATE(13), 6,
      sym__expression,
      sym__simple_expression,
      sym_binary_expression,
      sym__factor,
      sym_call_expression,
      sym_assignment,
  [1383] = 5,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      sym_identifier,
    ACTIONS(210), 1,
      sym_num_literal,
    STATE(18), 1,
      sym_variable,
    STATE(14), 6,
      sym__expression,
      sym__simple_expression,
      sym_binary_expression,
      sym__factor,
      sym_call_expression,
      sym_assignment,
  [1404] = 4,
    ACTIONS(212), 1,
      ts_builtin_sym_end,
    STATE(83), 1,
      sym_type_specifier,
    ACTIONS(5), 3,
      anon_sym_int,
      anon_sym_void,
      anon_sym_bool,
    STATE(55), 4,
      sym__declaration,
      sym_var_declaration,
      sym_function_declaration,
      aux_sym_program_repeat1,
  [1422] = 4,
    ACTIONS(214), 1,
      ts_builtin_sym_end,
    STATE(83), 1,
      sym_type_specifier,
    ACTIONS(216), 3,
      anon_sym_int,
      anon_sym_void,
      anon_sym_bool,
    STATE(55), 4,
      sym__declaration,
      sym_var_declaration,
      sym_function_declaration,
      aux_sym_program_repeat1,
  [1440] = 4,
    ACTIONS(219), 1,
      anon_sym_RPAREN,
    STATE(67), 1,
      sym_param,
    STATE(74), 1,
      sym_type_specifier,
    ACTIONS(5), 3,
      anon_sym_int,
      anon_sym_void,
      anon_sym_bool,
  [1455] = 3,
    STATE(71), 1,
      sym_param,
    STATE(74), 1,
      sym_type_specifier,
    ACTIONS(5), 3,
      anon_sym_int,
      anon_sym_void,
      anon_sym_bool,
  [1467] = 4,
    ACTIONS(221), 1,
      anon_sym_LBRACK,
    ACTIONS(223), 1,
      anon_sym_SEMI,
    ACTIONS(225), 1,
      anon_sym_LPAREN,
    STATE(72), 1,
      sym_param_list,
  [1480] = 1,
    ACTIONS(227), 4,
      ts_builtin_sym_end,
      anon_sym_int,
      anon_sym_void,
      anon_sym_bool,
  [1487] = 1,
    ACTIONS(229), 3,
      anon_sym_LPAREN,
      sym_identifier,
      sym_num_literal,
  [1493] = 1,
    ACTIONS(231), 3,
      anon_sym_LPAREN,
      sym_identifier,
      sym_num_literal,
  [1499] = 1,
    ACTIONS(233), 3,
      anon_sym_LPAREN,
      sym_identifier,
      sym_num_literal,
  [1505] = 3,
    ACTIONS(79), 1,
      anon_sym_COMMA,
    ACTIONS(235), 1,
      anon_sym_RPAREN,
    STATE(65), 1,
      aux_sym_arg_list_repeat1,
  [1515] = 3,
    ACTIONS(237), 1,
      anon_sym_COMMA,
    ACTIONS(239), 1,
      anon_sym_RPAREN,
    STATE(68), 1,
      aux_sym_param_list_repeat1,
  [1525] = 3,
    ACTIONS(83), 1,
      anon_sym_RPAREN,
    ACTIONS(241), 1,
      anon_sym_COMMA,
    STATE(65), 1,
      aux_sym_arg_list_repeat1,
  [1535] = 2,
    ACTIONS(244), 1,
      anon_sym_LBRACK,
    ACTIONS(246), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1543] = 3,
    ACTIONS(237), 1,
      anon_sym_COMMA,
    ACTIONS(248), 1,
      anon_sym_RPAREN,
    STATE(64), 1,
      aux_sym_param_list_repeat1,
  [1553] = 3,
    ACTIONS(250), 1,
      anon_sym_COMMA,
    ACTIONS(253), 1,
      anon_sym_RPAREN,
    STATE(68), 1,
      aux_sym_param_list_repeat1,
  [1563] = 2,
    ACTIONS(221), 1,
      anon_sym_LBRACK,
    ACTIONS(223), 1,
      anon_sym_SEMI,
  [1570] = 1,
    ACTIONS(255), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1575] = 1,
    ACTIONS(253), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1580] = 2,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    STATE(59), 1,
      sym_compound_statement,
  [1587] = 1,
    ACTIONS(257), 1,
      anon_sym_LBRACE,
  [1591] = 1,
    ACTIONS(259), 1,
      sym_identifier,
  [1595] = 1,
    ACTIONS(261), 1,
      sym_num_literal,
  [1599] = 1,
    ACTIONS(263), 1,
      anon_sym_LBRACE,
  [1603] = 1,
    ACTIONS(265), 1,
      anon_sym_RBRACK,
  [1607] = 1,
    ACTIONS(267), 1,
      anon_sym_SEMI,
  [1611] = 1,
    ACTIONS(269), 1,
      anon_sym_LBRACE,
  [1615] = 1,
    ACTIONS(271), 1,
      anon_sym_LPAREN,
  [1619] = 1,
    ACTIONS(273), 1,
      anon_sym_LPAREN,
  [1623] = 1,
    ACTIONS(275), 1,
      sym_identifier,
  [1627] = 1,
    ACTIONS(277), 1,
      sym_identifier,
  [1631] = 1,
    ACTIONS(279), 1,
      anon_sym_RBRACK,
  [1635] = 1,
    ACTIONS(281), 1,
      ts_builtin_sym_end,
  [1639] = 1,
    ACTIONS(283), 1,
      sym_identifier,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 60,
  [SMALL_STATE(4)] = 120,
  [SMALL_STATE(5)] = 168,
  [SMALL_STATE(6)] = 216,
  [SMALL_STATE(7)] = 264,
  [SMALL_STATE(8)] = 308,
  [SMALL_STATE(9)] = 352,
  [SMALL_STATE(10)] = 396,
  [SMALL_STATE(11)] = 425,
  [SMALL_STATE(12)] = 459,
  [SMALL_STATE(13)] = 487,
  [SMALL_STATE(14)] = 517,
  [SMALL_STATE(15)] = 549,
  [SMALL_STATE(16)] = 586,
  [SMALL_STATE(17)] = 618,
  [SMALL_STATE(18)] = 638,
  [SMALL_STATE(19)] = 660,
  [SMALL_STATE(20)] = 686,
  [SMALL_STATE(21)] = 705,
  [SMALL_STATE(22)] = 724,
  [SMALL_STATE(23)] = 755,
  [SMALL_STATE(24)] = 774,
  [SMALL_STATE(25)] = 805,
  [SMALL_STATE(26)] = 824,
  [SMALL_STATE(27)] = 843,
  [SMALL_STATE(28)] = 874,
  [SMALL_STATE(29)] = 905,
  [SMALL_STATE(30)] = 936,
  [SMALL_STATE(31)] = 955,
  [SMALL_STATE(32)] = 974,
  [SMALL_STATE(33)] = 1005,
  [SMALL_STATE(34)] = 1024,
  [SMALL_STATE(35)] = 1042,
  [SMALL_STATE(36)] = 1060,
  [SMALL_STATE(37)] = 1084,
  [SMALL_STATE(38)] = 1108,
  [SMALL_STATE(39)] = 1129,
  [SMALL_STATE(40)] = 1150,
  [SMALL_STATE(41)] = 1165,
  [SMALL_STATE(42)] = 1186,
  [SMALL_STATE(43)] = 1207,
  [SMALL_STATE(44)] = 1222,
  [SMALL_STATE(45)] = 1237,
  [SMALL_STATE(46)] = 1258,
  [SMALL_STATE(47)] = 1273,
  [SMALL_STATE(48)] = 1288,
  [SMALL_STATE(49)] = 1309,
  [SMALL_STATE(50)] = 1324,
  [SMALL_STATE(51)] = 1341,
  [SMALL_STATE(52)] = 1362,
  [SMALL_STATE(53)] = 1383,
  [SMALL_STATE(54)] = 1404,
  [SMALL_STATE(55)] = 1422,
  [SMALL_STATE(56)] = 1440,
  [SMALL_STATE(57)] = 1455,
  [SMALL_STATE(58)] = 1467,
  [SMALL_STATE(59)] = 1480,
  [SMALL_STATE(60)] = 1487,
  [SMALL_STATE(61)] = 1493,
  [SMALL_STATE(62)] = 1499,
  [SMALL_STATE(63)] = 1505,
  [SMALL_STATE(64)] = 1515,
  [SMALL_STATE(65)] = 1525,
  [SMALL_STATE(66)] = 1535,
  [SMALL_STATE(67)] = 1543,
  [SMALL_STATE(68)] = 1553,
  [SMALL_STATE(69)] = 1563,
  [SMALL_STATE(70)] = 1570,
  [SMALL_STATE(71)] = 1575,
  [SMALL_STATE(72)] = 1580,
  [SMALL_STATE(73)] = 1587,
  [SMALL_STATE(74)] = 1591,
  [SMALL_STATE(75)] = 1595,
  [SMALL_STATE(76)] = 1599,
  [SMALL_STATE(77)] = 1603,
  [SMALL_STATE(78)] = 1607,
  [SMALL_STATE(79)] = 1611,
  [SMALL_STATE(80)] = 1615,
  [SMALL_STATE(81)] = 1619,
  [SMALL_STATE(82)] = 1623,
  [SMALL_STATE(83)] = 1627,
  [SMALL_STATE(84)] = 1631,
  [SMALL_STATE(85)] = 1635,
  [SMALL_STATE(86)] = 1639,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_compound_statement_repeat2, 2), SHIFT_REPEAT(10),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_statement_repeat2, 2), SHIFT_REPEAT(46),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_statement_repeat2, 2), SHIFT_REPEAT(48),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_statement_repeat2, 2), SHIFT_REPEAT(3),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_compound_statement_repeat2, 2),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_compound_statement_repeat2, 2), SHIFT_REPEAT(80),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_compound_statement_repeat2, 2), SHIFT_REPEAT(81),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_compound_statement_repeat2, 2), SHIFT_REPEAT(36),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_statement_repeat2, 2), SHIFT_REPEAT(29),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 1),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 1),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, .production_id = 2),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, .production_id = 1),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, .production_id = 1),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arg_list_repeat1, 2),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 4),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 4),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__factor, 1),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__factor, 1),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_compound_statement_repeat1, 2),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_compound_statement_repeat1, 2),
  [99] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_compound_statement_repeat1, 2), SHIFT_REPEAT(86),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 2),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_expression, 2),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__factor, 3),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__factor, 3),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_list, 4),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg_list, 4),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound_statement, 2),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compound_statement, 2),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound_statement, 3),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compound_statement, 3),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_list, 2),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg_list, 2),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound_statement, 4),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compound_statement, 4),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_list, 3),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg_list, 3),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_declaration, 3),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var_declaration, 3),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_declaration, 6),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var_declaration, 6),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_selection_statement, 7),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selection_statement, 7),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 2),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 2),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 3),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 3),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_statement, 1),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_statement, 1),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_iteration_statement, 5),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_iteration_statement, 5),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_statement, 2),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_statement, 2),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_selection_statement, 5),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selection_statement, 5),
  [204] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2),
  [216] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(86),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 4),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mul_op, 1),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_add_op, 1),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rel_op, 1),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [241] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arg_list_repeat1, 2), SHIFT_REPEAT(41),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 2),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [250] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_param_list_repeat1, 2), SHIFT_REPEAT(57),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_param_list_repeat1, 2),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 4),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_list, 3),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_list, 2),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_list, 4),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [281] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_specifier, 1),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_cm(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const unsigned short *)ts_parse_table,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .symbol_names = ts_symbol_names,
    .public_symbol_map = ts_symbol_map,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .field_count = FIELD_COUNT,
    .field_names = ts_field_names,
    .field_map_slices = (const TSFieldMapSlice *)ts_field_map_slices,
    .field_map_entries = (const TSFieldMapEntry *)ts_field_map_entries,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
